---
- hosts: all
  tasks:
    - name: install lastest version nginx
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: ocopy the nginx config file and restart nginx 
      copy:
        src: /etc/ansible/static_site.cfg
        dest: /etc/nginx/sites-available/static_site.cfg
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: copy the content of the web site
      copy:
        src: /etc/ansible/index.html
        dest: /home/vincephng/web/index.html
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
